name: Generate files
on: [push]
jobs:
  generate:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install encore
        run: |
          curl -L https://encore.dev/install.sh | bash
          echo "$HOME/.encore/bin" >> $GITHUB_PATH

      - name: Setup encore
        run: encore auth login --auth-key=$ENCORE_AUTH_KEY
        env:
          ANDREW_ENVIRONMENT: staging
          ENCORE_AUTH_KEY: ${{ secrets.ENCORE_AUTH_KEY }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Generate files
        run: yarn generate
        env:
          ANDREW_ENVIRONMENT: staging
          ENCORE_APP_ID: andrew-naz2

      - name: Check no changes after generating files
        run: echo $(git --no-pager diff) | grep -e "^\$"

      - name: Output diff
        run: |
          echo "\`\`\`diff" >> $GITHUB_STEP_SUMMARY
          git --no-pager diff --no-color >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        if: ${{ failure() }}
